name: 'Update *.nuspec'
description: 'A Github action that scans .NET projects, and update in nuspec-file dependencies node.'
branding:
  icon: activity
  color: yellow
inputs:
  dir:
    description: 'Directory to scan for .csproj and .nuspec files (repository root in workflows: /github/workspace)'
    required: false
    default: '/github/workspace'
#outputs:
#  upgrade-projects:
#    description: 'An array of projects that need to be upgraded.'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  image: 'docker://ghcr.io/some-user/some-registry' # Starting with docker:// is important!!
  args:
    - ${{ inputs.dir }}
