name: CI

on:
  push:
    branches:
      - master
      - release/*
      - hotfix/*
  pull_request:
  workflow_dispatch:

jobs:
  version:
    uses: ./.github/workflows/version.yml

  release-binaries:
    needs: version
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/release-binaries.yml
    with:
      version: ${{ needs.version.outputs.version }}
      publish_artifacts: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/')) }}

  build:
    needs:
      - version
      - release-binaries
    permissions:
      contents: write
      packages: write
      actions: read
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version.outputs.version }}
      major: ${{ needs.version.outputs.major }}
      minor: ${{ needs.version.outputs.minor }}
      channel: ${{ needs.version.outputs.channel }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      TAGTOKEN: ${{ secrets.TAGTOKEN }}
      AZDO_MARKETPLACE_PAT: ${{ secrets.AZDO_MARKETPLACE_PAT }}

  publish-github-release:
    needs:
      - version
      - build
      - release-binaries
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/')) }}
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/publish-github-release.yml
    with:
      version: ${{ needs.version.outputs.version }}
      prerelease: ${{ needs.version.outputs.prerelease }}

  publish-homebrew:
    needs:
      - version
      - build
      - release-binaries
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    permissions:
      contents: read
    uses: ./.github/workflows/publish-homebrew.yml
    with:
      version: ${{ needs.version.outputs.version }}
    secrets:
      TAGTOKEN: ${{ secrets.TAGTOKEN }}
      HOMEBREW_GITHUB_API_KEY: ${{ secrets.HOMEBREW_GITHUB_API_KEY }}

  publish-chocolatey:
    needs:
      - version
      - build
      - release-binaries
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/')) }}
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/publish-chocolatey.yml
    with:
      version: ${{ needs.version.outputs.version }}
    secrets:
      CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
